package enums;

public enum Context {

    BASKET_PRODUCT_NAME,
    BASKET_PRODUCT_SUBTOTAL_PRICE,
    ORDER_PRODUCT_SUBTOTAL_PRICE,
    ORDER_PRODUCT_TOTAL_PRICE,
    CHOSEN_PAYMENT_METHOD,
    BASKET_SIZE

}
